- name: Setup Archcraft installation
  hosts: all
  tasks:
    - name: Install all packages via yay
      ansible.builtin.shell: /usr/bin/yay -S --noconfirm {{ item }}
      with_items:
        - vi-vim-symlink
        - snapd
        - asdf-vm
        - jetbrains-toolbox

    # If you have a zshrc, then set it up
    - name: zshrc file stat
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.zshrc"
      register: zshrc

    - name: Setup zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: '. /opt/asdf-vm/asdf.sh'
      when: zshrc.stat.isreg

    # If you have a bashrc, then set it up
    - name: bashrc file stat
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.bashrc"
      register: bashrc

    - name: Setup bashrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: '. /opt/asdf-vm/asdf.sh'
      when: bashrc.stat.isreg

    - name: Install asdf tools
      ansible.builtin.shell: |
        asdf plugin add {{ item.name }}
        asdf install {{ item.name }} {{ item.version }}
        asdf global {{ item.name }} {{ item.version }}

      with_items:
        - name: awscli
          version: 2.13.11
          global: 2.13.11

        - name: elixir
          version: 1.12.2-otp-24
          global: 1.12.2-otp-24

        - name: erlang
          version: 24.0.3
          global: 24.0.3

        - name: golang
          version: 1.20.6
          global: 1.20.6

        - name: java
          version: openjdk-11.0.2
          global: openjdk-11.0.2

        - name: maven
          version: 3.6.3
          global: 3.6.3

        - name: mongosh
          version: 1.2.3
          global: 1.2.3

        - name: nodejs
          version: 18.13.0
          global: 18.13.0

        - name: packer
          version: 1.7.4
          global: 1.7.4

        - name: python
          version: 3.8.12
          global: 3.8.12

        - name: swag
          version: 1.8.7
          global: 1.8.7

        - name: terraform
          version: 0.15.5
          global: 1.8.7

    - name: Sudo commands
      become: true
      become_user: root
      become_method: sudo
      become_flags: -i
      block:
        - name: Create snap symlink for classic support
          ansible.builtin.file:
            src: /var/lib/snapd/snap
            dest: /snap
            owner: root
            group: root
            state: link

        - name: Enable snapd.socket
          ansible.builtin.systemd:
            name: snapd.socket
            enabled: true
            state: started

        - name: Enable snapd.apparmor
          ansible.builtin.systemd:
            name: snapd.apparmor
            enabled: true
            state: started

        - name: Disable bluetooth by default
          ansible.builtin.systemd:
            name: bluetooth.service
            enabled: false
            state: stopped

        - name: pacman packages
          community.general.pacman:
            state: present
            name:
              - podman
              - podman-compose

        - name: Install all gui applications that don't require classic snap support for installation
          community.general.snap:
            name:
              - whatsdesk
              - brave
              - discord
              - dbeaver-ce
              - remmina
              - insomnia
              - teams-for-linux
              - 1password

        - name: Install all gui applications that require classic snap support for installation
          community.general.snap:
            classic: true
            name:
              - sublime-merge
              - code

        - name: Install all gui applications that are in --edge
          community.general.snap:
            channel: edge
            name:
              - calibre

        - name: Set default browser to brave
          ansible.builtin.lineinfile:
            path: "/etc/environment"
            search_string: "BROWSER="
            line: 'BROWSER=brave'


        # Replace this once evolution becomes available on snap
        - name: Install flatpak for evolution
          community.general.pacman:
            state: present
            name:
              - xdg-desktop-portal-hyprland
              - flatpak

        - name: install evolution via flatpak
          community.general.flatpak:
            state: present
            name: org.gnome.Evolution

        - name: install unityhub via flatpak
          community.general.flatpak:
            state: present
            name: com.unity.UnityHub
