- name: Check if pacman is installed
  shell: command -v pacman >/dev/null 2>&1
  register: pacman_exists
  ignore_errors: yes

- name: pacman commands
  when: pacman_exists.rc == 0
  block:
    - name: Install all packages via yay
      ansible.builtin.shell: /usr/bin/yay -S --noconfirm {{ item }}
      with_items:
        - asdf-vm

    # If you have a zshrc, then set it up
    - name: zshrc file stat
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.zshrc"
      register: zshrc

    - name: Setup zshrc
      ansible.builtin.lineinfile:
        path: "{{ zshrc.stat.path }}"
        line: . /opt/asdf-vm/asdf.sh
      when: zshrc.stat.exists and zshrc.stat.isreg

    # If you have a bashrc, then set it up
    - name: bashrc file stat
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.bashrc"
      register: bashrc

    - name: Setup bashrc
      ansible.builtin.lineinfile:
        path: "{{ bashrc.stat.path }}"
        line: . /opt/asdf-vm/asdf.sh
      when: bashrc.stat.exists and bashrc.stat.isreg

    - name: Install asdf tool dependencies
      become: true
      become_user: root
      become_method: sudo
      become_flags: -i
      community.general.pacman:
        name: 
          - base-devel
          - unixodbc
          - wxwidgets-gtk3
        state: present

    - name: Install asdf tools
      ansible.builtin.shell: |
        source /opt/asdf-vm/asdf.sh
        asdf plugin add {{ item.name }}
        asdf install {{ item.name }} {{ item.version }}
        asdf global {{ item.name }} {{ item.version }}

      # TODO: extract this into a var, and make the versions propery an array
      with_items:
        - name: awscli
          version: 2.13.11
          global: 2.13.11

        - name: elixir
          version: 1.12.2-otp-24
          global: 1.12.2-otp-24

        - name: erlang
          version: 26.0.2
          global: 26.0.2

        - name: golang
          version: 1.20.6
          global: 1.20.6

        - name: java
          version: openjdk-11.0.2
          global: openjdk-11.0.2

        - name: maven
          version: 3.6.3
          global: 3.6.3

        - name: mongosh
          version: 1.2.3
          global: 1.2.3

        - name: nodejs
          version: 18.13.0
          global: 18.13.0

        - name: packer
          version: 1.7.4
          global: 1.7.4

        - name: python
          version: 3.8.12
          global: 3.8.12

        - name: swag
          version: 1.8.7
          global: 1.8.7

        - name: terraform
          version: 0.15.5
          global: 1.8.7
