#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Script To Manage Brightness For Archcraft (in Wayland).

WM='hypr'
iDIR="$HOME/.config/$WM/mako/icons"

# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" `light -G`)
	echo "${LIGHT}%"
}

# Get icons
get_icon() {
	backlight="$(get_backlight)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "20") ]]; then
		icon="$iDIR"/brightness-20.png
	elif [[ ("$current" -ge "20") && ("$current" -le "40") ]]; then
		icon="$iDIR"/brightness-40.png
	elif [[ ("$current" -ge "40") && ("$current" -le "60") ]]; then
		icon="$iDIR"/brightness-60.png
	elif [[ ("$current" -ge "60") && ("$current" -le "80") ]]; then
		icon="$iDIR"/brightness-80.png
	elif [[ ("$current" -ge "80") && ("$current" -le "100") ]]; then
		icon="$iDIR"/brightness-100.png
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify-backlight -u low -i "$icon" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
	brightness=$(light)
	if (( $(echo "$brightness == 0" | bc -l) )); then
		light -S 1
	elif (( $(echo "$brightness < 5" | bc -l) )); then
		light -S 5
	else
		light -A 5
	fi
	get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightness=$(light)
	if (( $(echo "$brightness == 1" | bc -l) )); then
		light -S 0
	elif (( $(echo "$brightness <= 5" | bc -l) )); then
		light -S 1
	else
		light -U 5
	fi
	get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
