
# hyprland configurations
- name: hyprland.conf file stat
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/hypr"
  register: hypr

- name: set hyprland configs
  when: hypr.stat.exists and hypr.stat.isdir
  block:
    - name: Install custom hypr configs
      ansible.builtin.copy:
        src: files/.config/hypr/
        dest: "{{ hypr.stat.path }}/"
        mode: "preserve"
        force: true

    - name: Set default hyprland browser to brave
      ansible.builtin.lineinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        regexp: '^\$browser.*'
        line: '$browser = brave'

    - name: Set default hyprland editor to vscode
      ansible.builtin.lineinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        regexp: '^\$editor.*'
        line: '$editor = code'

    - name: Set rofi_clipboard executable
      ansible.builtin.lineinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        regexp: '^\$rofi_clipboard   ='
        insertafter: '^\$rofi_screenshot  ='
        line: '$rofi_clipboard   = ~/.config/hypr/scripts/rofi_clipboard'

    - name: Set rofi_clipboard binding
      ansible.builtin.lineinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        regexp: '^bind  = SUPER, V,'
        insertafter: '^\# -- Rofi --'
        line: 'bind  = SUPER, V,       exec, $rofi_clipboard'

    - name: Set custom configurations
      ansible.builtin.blockinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        marker: "#-- {mark} - ansible managed - device controls"
        block: |
          device:pixa3854:00-093a:0274-touchpad {
              sensitivity = 0.60
          }

    - name: Set custom configurations
      ansible.builtin.blockinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        marker: "#-- {mark} - ansible managed - startup apps"
        block: |
          # cliphist integration
          exec-once = wl-paste --type text --watch cliphist store
          exec-once = wl-paste --type image --watch cliphist store

          # startup apps
          exec-once=[workspace 1 silent] /var/lib/snapd/snap/bin/brave
          exec-once=[workspace 2 silent] /var/lib/snapd/snap/bin/discord
          exec-once=[workspace 2 silent] /var/lib/snapd/snap/bin/teams-for-linux --minimized
          exec-once=[workspace 2 silent] /var/lib/snapd/snap/bin/whatsdesk
          exec-once=[workspace 2 silent] /var/lib/snapd/snap/bin/1password --silent
          exec-once=[workspace 2 silent] /usr/bin/jetbrains-toolbox --minimize
          exec-once=[workspace 3 silent] /var/lib/snapd/snap/bin/thunderbird

