
# hyprland configurations
- name: hyprland.conf file stat
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/hypr"
  register: hypr

- name: set hyprland configs
  when: hypr.stat.exists and hypr.stat.isdir
  block:
    - name: Install custom hypr configs
      ansible.builtin.copy:
        src: files/.config/hypr/
        dest: "{{ hypr.stat.path }}/"
        mode: "preserve"
        force: true

    - name: Set default hyprland browser to brave
      ansible.builtin.lineinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        regexp: '^\$browser.*'
        line: '$browser = brave'

    - name: Set default hyprland editor to vscode
      ansible.builtin.lineinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        regexp: '^\$editor.*'
        line: '$editor = code'

    - name: Set custom configurations
      ansible.builtin.blockinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        marker: "#-- {mark} - ansible managed - device controls"
        block: |
          device:pixa3854:00-093a:0274-touchpad {
              sensitivity = 0.60
          }

    - name: Set custom configurations
      ansible.builtin.blockinfile:
        path: "{{ hypr.stat.path }}/hyprland.conf"
        marker: "#-- {mark} - ansible managed - startup apps"
        block: |
          exec-once=[workspace 1 silent] /var/lib/snapd/snap/bin/brave
          exec-once=[workspace 2 silent] /var/lib/snapd/snap/bin/discord
          exec-once=[workspace 2 silent] /var/lib/snapd/snap/bin/teams-for-linux
          exec-once=[workspace 2 silent] /var/lib/snapd/snap/bin/whatsdesk
          exec-once=[workspace 2 silent] /var/lib/flatpak/exports/bin/org.gnome.Evolution
          exec-once=[workspace 2 silent] /var/lib/snapd/snap/bin/1password
          exec-once=[workspace 2 silent] /usr/bin/jetbrains-toolbox
